load('/Users/benson/Desktop/gitprojs/d3cc/cut_data.mat');

close all;

%%
if 1
single_msp_plot(soc_Epinions1_filter_dl_d3c_cond, ...
                soc_Epinions1_filter_lap_d3c_cond, ...
                soc_Epinions1_filter_alap_d3c_cond, ...
                soc_Epinions1_filter_msc_d3c_cond, ...
                soc_Epinions1_filter_cocluster_u_d3c_cond, ...
                soc_Epinions1_filter_cocluster_v_d3c_cond, ...
                soc_Epinions1_filter_random_d3c_cond, ...
                'soc-Epinions1', 0);

single_msp_plot(soc_Epinions1_filter_dl_d3c_cond, ...
                soc_Epinions1_filter_lap_d3c_cond, ...
                soc_Epinions1_filter_alap_d3c_cond, ...
                soc_Epinions1_filter_msc_d3c_cond, ...
                soc_Epinions1_filter_cocluster_u_d3c_cond, ...
                soc_Epinions1_filter_cocluster_v_d3c_cond, ...
                soc_Epinions1_filter_random_d3c_cond, ...
                'legend', 1);     

single_msp_plot(wiki_Vote_filter_dl_d3c_cond, ...
                wiki_Vote_filter_lap_d3c_cond, ...
                wiki_Vote_filter_alap_d3c_cond, ...
                wiki_Vote_filter_msc_d3c_cond, ...
                wiki_Vote_filter_cocluster_u_d3c_cond, ...
                wiki_Vote_filter_cocluster_v_d3c_cond, ...
                wiki_Vote_filter_random_d3c_cond, ...
                'wiki-Vote', 0);
            
single_msp_plot(amazon0312_filter_dl_d3c_cond, ...
                amazon0312_filter_lap_d3c_cond, ...
                amazon0312_filter_alap_d3c_cond, ...
                amazon0312_filter_msc_d3c_cond, ...
                amazon0312_filter_cocluster_u_d3c_cond, ...
                amazon0312_filter_cocluster_v_d3c_cond, ...
                amazon0312_filter_random_d3c_cond, ...
                'amazon0312', 0);
            
single_msp_plot(email_Enron_filter_dl_d3c_cond, ...
                email_Enron_filter_lap_d3c_cond, ...
                email_Enron_filter_alap_d3c_cond, ...
                email_Enron_filter_msc_d3c_cond, ...
                email_Enron_filter_cocluster_u_d3c_cond, ...
                email_Enron_filter_cocluster_v_d3c_cond, ...
                email_Enron_filter_random_d3c_cond, ...
                'email-Enron', 0);

single_msp_plot(email_EuAll_filter_dl_d3c_cond, ...
                email_EuAll_filter_lap_d3c_cond, ...
                email_EuAll_filter_alap_d3c_cond, ...
                email_EuAll_filter_msc_d3c_cond, ...
                email_EuAll_filter_cocluster_u_d3c_cond, ...
                email_EuAll_filter_cocluster_v_d3c_cond, ...
                email_EuAll_filter_random_d3c_cond, ...
                'email-EuAll', 0); 

single_msp_plot(twitter_combined_filter_dl_d3c_cond, ...
                twitter_combined_filter_lap_d3c_cond, ...
                twitter_combined_filter_alap_d3c_cond, ...
                twitter_combined_filter_msc_d3c_cond, ...
                twitter_combined_filter_cocluster_u_d3c_cond, ...
                twitter_combined_filter_cocluster_v_d3c_cond, ...
                twitter_combined_filter_random_d3c_cond, ...
                'twitter_combined', 0);
            
single_msp_plot(soc_Slashdot0811_filter_dl_d3c_cond, ...
                soc_Slashdot0811_filter_lap_d3c_cond, ...
                soc_Slashdot0811_filter_alap_d3c_cond, ...
                soc_Slashdot0811_filter_msc_d3c_cond, ...
                soc_Slashdot0811_filter_cocluster_u_d3c_cond, ...
                soc_Slashdot0811_filter_cocluster_v_d3c_cond, ...
                soc_Slashdot0811_filter_random_d3c_cond, ...
                'soc-Slashdot0811', 0);
            
single_msp_plot(web_Stanford_filter_dl_d3c_cond, ...
                web_Stanford_filter_lap_d3c_cond, ...
                web_Stanford_filter_alap_d3c_cond, ...
                web_Stanford_filter_msc_d3c_cond, ...
                web_Stanford_filter_cocluster_u_d3c_cond, ...
                web_Stanford_filter_cocluster_v_d3c_cond, ...
                web_Stanford_filter_random_d3c_cond, ...
                'web-Stanford', 0);
            
single_msp_plot(as_caida20071105_filter_dl_d3c_cond, ...
                as_caida20071105_filter_lap_d3c_cond, ...
                as_caida20071105_filter_alap_d3c_cond, ...
                as_caida20071105_filter_msc_d3c_cond, ...
                as_caida20071105_filter_cocluster_u_d3c_cond, ...
                as_caida20071105_filter_cocluster_v_d3c_cond, ...
                as_caida20071105_filter_random_d3c_cond, ...
                'as-caida20071105', 0);  
            

single_msp_plot(wiki_RfA_net_filter_dl_d3c_cond, ...
                wiki_RfA_net_filter_lap_d3c_cond, ...
                wiki_RfA_net_filter_alap_d3c_cond, ...
                wiki_RfA_net_filter_msc_d3c_cond, ...
                wiki_RfA_net_filter_cocluster_u_d3c_cond, ...
                wiki_RfA_net_filter_cocluster_v_d3c_cond, ...
                wiki_RfA_net_filter_random_d3c_cond, ...
                'wiki-RfA', 0);            
            
single_msp_plot(wiki_Talk_filter_dl_d3c_cond, ...
                wiki_Talk_filter_lap_d3c_cond, ...
                wiki_Talk_filter_alap_d3c_cond, ...
                wiki_Talk_filter_msc_d3c_cond, ...
                wiki_Talk_filter_cocluster_u_d3c_cond, ...
                wiki_Talk_filter_cocluster_v_d3c_cond, ...
                wiki_Talk_filter_random_d3c_cond, ...
                'wiki-Talk', 0);
end

%%
if 1
single_msp_plot_exp(soc_Epinions1_filter_dl_num_cut, ...
                soc_Epinions1_filter_lap_num_cut, ...
                soc_Epinions1_filter_alap_num_cut, ...
                soc_Epinions1_filter_msc_num_cut, ...
                soc_Epinions1_filter_cocluster_u_num_cut, ...
                soc_Epinions1_filter_cocluster_v_num_cut, ...
                soc_Epinions1_filter_random_num_cut, ...
                'soc-Epinions1', 0);

single_msp_plot_exp(soc_Epinions1_filter_dl_num_cut, ...
                soc_Epinions1_filter_lap_num_cut, ...
                soc_Epinions1_filter_alap_num_cut, ...
                soc_Epinions1_filter_msc_num_cut, ...
                soc_Epinions1_filter_cocluster_u_num_cut, ...
                soc_Epinions1_filter_cocluster_v_num_cut, ...
                soc_Epinions1_filter_random_num_cut, ...
                'legend', 1);     

single_msp_plot_exp(wiki_Vote_filter_dl_num_cut, ...
                wiki_Vote_filter_lap_num_cut, ...
                wiki_Vote_filter_alap_num_cut, ...
                wiki_Vote_filter_msc_num_cut, ...
                wiki_Vote_filter_cocluster_u_num_cut, ...
                wiki_Vote_filter_cocluster_v_num_cut, ...
                wiki_Vote_filter_random_num_cut, ...
                'wiki-Vote', 0);
            
single_msp_plot_exp(amazon0312_filter_dl_num_cut, ...
                amazon0312_filter_lap_num_cut, ...
                amazon0312_filter_alap_num_cut, ...
                amazon0312_filter_msc_num_cut, ...
                amazon0312_filter_cocluster_u_num_cut, ...
                amazon0312_filter_cocluster_v_num_cut, ...
                amazon0312_filter_random_num_cut, ...
                'amazon0312', 0);
            
single_msp_plot_exp(email_Enron_filter_dl_num_cut, ...
                email_Enron_filter_lap_num_cut, ...
                email_Enron_filter_alap_num_cut, ...
                email_Enron_filter_msc_num_cut, ...
                email_Enron_filter_cocluster_u_num_cut, ...
                email_Enron_filter_cocluster_v_num_cut, ...
                email_Enron_filter_random_num_cut, ...
                'email-Enron', 0);

single_msp_plot_exp(email_EuAll_filter_dl_num_cut, ...
                email_EuAll_filter_lap_num_cut, ...
                email_EuAll_filter_alap_num_cut, ...
                email_EuAll_filter_msc_num_cut, ...
                email_EuAll_filter_cocluster_u_num_cut, ...
                email_EuAll_filter_cocluster_v_num_cut, ...
                email_EuAll_filter_random_num_cut, ...
                'email-EuAll', 0); 

single_msp_plot_exp(twitter_combined_filter_dl_num_cut, ...
                twitter_combined_filter_lap_num_cut, ...
                twitter_combined_filter_alap_num_cut, ...
                twitter_combined_filter_msc_num_cut, ...
                twitter_combined_filter_cocluster_u_num_cut, ...
                twitter_combined_filter_cocluster_v_num_cut, ...
                twitter_combined_filter_random_num_cut, ...
                'twitter_combined', 0);
            
single_msp_plot_exp(soc_Slashdot0811_filter_dl_num_cut, ...
                soc_Slashdot0811_filter_lap_num_cut, ...
                soc_Slashdot0811_filter_alap_num_cut, ...
                soc_Slashdot0811_filter_msc_num_cut, ...
                soc_Slashdot0811_filter_cocluster_u_num_cut, ...
                soc_Slashdot0811_filter_cocluster_v_num_cut, ...
                soc_Slashdot0811_filter_random_num_cut, ...
                'soc-Slashdot0811', 0);
            
single_msp_plot_exp(web_Stanford_filter_dl_num_cut, ...
                web_Stanford_filter_lap_num_cut, ...
                web_Stanford_filter_alap_num_cut, ...
                web_Stanford_filter_msc_num_cut, ...
                web_Stanford_filter_cocluster_u_num_cut, ...
                web_Stanford_filter_cocluster_v_num_cut, ...
                web_Stanford_filter_random_num_cut, ...
                'web-Stanford', 0);
            
single_msp_plot_exp(as_caida20071105_filter_dl_num_cut, ...
                as_caida20071105_filter_lap_num_cut, ...
                as_caida20071105_filter_alap_num_cut, ...
                as_caida20071105_filter_msc_num_cut, ...
                as_caida20071105_filter_cocluster_u_num_cut, ...
                as_caida20071105_filter_cocluster_v_num_cut, ...
                as_caida20071105_filter_random_num_cut, ...
                'as-caida20071105', 0);  
            

single_msp_plot_exp(wiki_RfA_net_filter_dl_num_cut, ...
                wiki_RfA_net_filter_lap_num_cut, ...
                wiki_RfA_net_filter_alap_num_cut, ...
                wiki_RfA_net_filter_msc_num_cut, ...
                wiki_RfA_net_filter_cocluster_u_num_cut, ...
                wiki_RfA_net_filter_cocluster_v_num_cut, ...
                wiki_RfA_net_filter_random_num_cut, ...
                'wiki-RfA', 0); 
            
single_msp_plot_exp(wiki_Talk_filter_dl_num_cut, ...
                wiki_Talk_filter_lap_num_cut, ...
                wiki_Talk_filter_alap_num_cut, ...
                wiki_Talk_filter_msc_num_cut, ...
                wiki_Talk_filter_cocluster_u_num_cut, ...
                wiki_Talk_filter_cocluster_v_num_cut, ...
                wiki_Talk_filter_random_num_cut, ...
                'wiki-Talk', 0);
end

%%
if 1
single_msp_plot_density(soc_Epinions1_filter_dl_density, ...
                soc_Epinions1_filter_lap_density, ...
                soc_Epinions1_filter_alap_density, ...
                soc_Epinions1_filter_msc_density, ...
                soc_Epinions1_filter_cocluster_u_density, ...
                soc_Epinions1_filter_cocluster_v_density, ...
                soc_Epinions1_filter_random_density, ...
                'soc-Epinions1', 0);

single_msp_plot_density(soc_Epinions1_filter_dl_density, ...
                soc_Epinions1_filter_lap_density, ...
                soc_Epinions1_filter_alap_density, ...
                soc_Epinions1_filter_msc_density, ...
                soc_Epinions1_filter_cocluster_u_density, ...
                soc_Epinions1_filter_cocluster_v_density, ...
                soc_Epinions1_filter_random_density, ...
                'legend', 1);     

single_msp_plot_density(wiki_Vote_filter_dl_density, ...
                wiki_Vote_filter_lap_density, ...
                wiki_Vote_filter_alap_density, ...
                wiki_Vote_filter_msc_density, ...
                wiki_Vote_filter_cocluster_u_density, ...
                wiki_Vote_filter_cocluster_v_density, ...
                wiki_Vote_filter_random_density, ...
                'wiki-Vote', 0);
            
single_msp_plot_density(amazon0312_filter_dl_density, ...
                amazon0312_filter_lap_density, ...
                amazon0312_filter_alap_density, ...
                amazon0312_filter_msc_density, ...
                amazon0312_filter_cocluster_u_density, ...
                amazon0312_filter_cocluster_v_density, ...
                amazon0312_filter_random_density, ...
                'amazon0312', 0);
            
single_msp_plot_density(email_Enron_filter_dl_density, ...
                email_Enron_filter_lap_density, ...
                email_Enron_filter_alap_density, ...
                email_Enron_filter_msc_density, ...
                email_Enron_filter_cocluster_u_density, ...
                email_Enron_filter_cocluster_v_density, ...
                email_Enron_filter_random_density, ...
                'email-Enron', 0);

single_msp_plot_density(email_EuAll_filter_dl_density, ...
                email_EuAll_filter_lap_density, ...
                email_EuAll_filter_alap_density, ...
                email_EuAll_filter_msc_density, ...
                email_EuAll_filter_cocluster_u_density, ...
                email_EuAll_filter_cocluster_v_density, ...
                email_EuAll_filter_random_density, ...
                'email-EuAll', 0); 

single_msp_plot_density(twitter_combined_filter_dl_density, ...
                twitter_combined_filter_lap_density, ...
                twitter_combined_filter_alap_density, ...
                twitter_combined_filter_msc_density, ...
                twitter_combined_filter_cocluster_u_density, ...
                twitter_combined_filter_cocluster_v_density, ...
                twitter_combined_filter_random_density, ...
                'twitter_combined', 0);
            
single_msp_plot_density(soc_Slashdot0811_filter_dl_density, ...
                soc_Slashdot0811_filter_lap_density, ...
                soc_Slashdot0811_filter_alap_density, ...
                soc_Slashdot0811_filter_msc_density, ...
                soc_Slashdot0811_filter_cocluster_u_density, ...
                soc_Slashdot0811_filter_cocluster_v_density, ...
                soc_Slashdot0811_filter_random_density, ...
                'soc-Slashdot0811', 0);
            
single_msp_plot_density(web_Stanford_filter_dl_density, ...
                web_Stanford_filter_lap_density, ...
                web_Stanford_filter_alap_density, ...
                web_Stanford_filter_msc_density, ...
                web_Stanford_filter_cocluster_u_density, ...
                web_Stanford_filter_cocluster_v_density, ...
                web_Stanford_filter_random_density, ...
                'web-Stanford', 0);
            
single_msp_plot_density(as_caida20071105_filter_dl_density, ...
                as_caida20071105_filter_lap_density, ...
                as_caida20071105_filter_alap_density, ...
                as_caida20071105_filter_msc_density, ...
                as_caida20071105_filter_cocluster_u_density, ...
                as_caida20071105_filter_cocluster_v_density, ...
                as_caida20071105_filter_random_density, ...
                'as-caida20071105', 0);  
            

single_msp_plot_density(wiki_RfA_net_filter_dl_density, ...
                wiki_RfA_net_filter_lap_density, ...
                wiki_RfA_net_filter_alap_density, ...
                wiki_RfA_net_filter_msc_density, ...
                wiki_RfA_net_filter_cocluster_u_density, ...
                wiki_RfA_net_filter_cocluster_v_density, ...
                wiki_RfA_net_filter_random_density, ...
                'wiki-RfA', 0);
            
end
if 1       
single_msp_plot_density(wiki_Talk_filter_dl_density, ...
                wiki_Talk_filter_lap_density, ...
                wiki_Talk_filter_alap_density, ...
                wiki_Talk_filter_msc_density, ...
                wiki_Talk_filter_cocluster_u_density, ...
                wiki_Talk_filter_cocluster_v_density, ...
                wiki_Talk_filter_random_density, ...
                'wiki-Talk', 1);
end
            
            
